version: "3.4"

services:
    db:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        ports:
          - "1433:1433"
        environment:
            SA_PASSWORD: "PASSWORD"
            ACCEPT_EULA: "Y"
    api:
        volumes:
          - /app
          - /src
          - /app/publish
          - /app/build
        build:
          context: .
          dockerfile: Dockerfile
        ports:
          - "8080:80"
        depends_on:
          - db